//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.12.06 at 02:26:09 PM CST 
//


package com.example.demo.soap.ws;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.example.demo.soap.ws package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.example.demo.soap.ws
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link DeleteTaskRequest }
     * 
     */
    public DeleteTaskRequest createDeleteTaskRequest() {
        return new DeleteTaskRequest();
    }

    /**
     * Create an instance of {@link GetTaskByIdRequest }
     * 
     */
    public GetTaskByIdRequest createGetTaskByIdRequest() {
        return new GetTaskByIdRequest();
    }

    /**
     * Create an instance of {@link GetTaskByIdResponse }
     * 
     */
    public GetTaskByIdResponse createGetTaskByIdResponse() {
        return new GetTaskByIdResponse();
    }

    /**
     * Create an instance of {@link TaskInfo }
     * 
     */
    public TaskInfo createTaskInfo() {
        return new TaskInfo();
    }

    /**
     * Create an instance of {@link AddTaskRequest }
     * 
     */
    public AddTaskRequest createAddTaskRequest() {
        return new AddTaskRequest();
    }

    /**
     * Create an instance of {@link AddTaskResponse }
     * 
     */
    public AddTaskResponse createAddTaskResponse() {
        return new AddTaskResponse();
    }

    /**
     * Create an instance of {@link UpdateTaskResponse }
     * 
     */
    public UpdateTaskResponse createUpdateTaskResponse() {
        return new UpdateTaskResponse();
    }

    /**
     * Create an instance of {@link GetAllTasksRequest }
     * 
     */
    public GetAllTasksRequest createGetAllTasksRequest() {
        return new GetAllTasksRequest();
    }

    /**
     * Create an instance of {@link GetAllTaskResponse }
     * 
     */
    public GetAllTaskResponse createGetAllTaskResponse() {
        return new GetAllTaskResponse();
    }

    /**
     * Create an instance of {@link TaskList }
     * 
     */
    public TaskList createTaskList() {
        return new TaskList();
    }

    /**
     * Create an instance of {@link DeleteTaskResponse }
     * 
     */
    public DeleteTaskResponse createDeleteTaskResponse() {
        return new DeleteTaskResponse();
    }

    /**
     * Create an instance of {@link UpdatedTaskRequest }
     * 
     */
    public UpdatedTaskRequest createUpdatedTaskRequest() {
        return new UpdatedTaskRequest();
    }

}
