//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.01.25 at 01:13:16 PM CST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.soap.demo.example.com/api/taskTracker", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.example.demo.soap.ws.components;
